name: eternal_fire_static
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # StateManagment
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  hive: ^2.2.3

  # Image
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.2
  flutter_svg: ^2.0.10+1

  # Network
  dio: ^5.5.0+1
  url_launcher: ^6.3.0

  # Localization
  easy_localization: ^3.0.7

  # Router
  auto_route: ^9.2.2

  # Security
  flutter_dotenv: ^5.1.0

  # Util
  json_annotation: ^4.9.0
  path_provider: ^2.1.3


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Router
  auto_route_generator: ^9.0.0

  # StateManagment
  mobx_codegen: ^2.6.1
  hive_generator: ^2.0.1

  build_runner: ^2.4.11


flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/flag/
    - assets/localization/
    - assets/.env